### ISSUE TITLE
Possible issue... trying java updates

### ISSUE THREAD

**Issue by laritakr** [fcrepo/fcrepo#1178]
@escowles 

```console
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

```console
ERROR 12:22:08.881 (RepositoryNodeTypeManager) Node types were read from the system content, and appear to be inconsistent or invalid: repo
org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:157)
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:46)
	at org.modeshape.jcr.cache.document.DocumentTranslator.childReferenceFrom(DocumentTranslator.java:966)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences$Medium.<init>(ImmutableChildReferences.java:220)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences.create(ImmutableChildReferences.java:53)
	at org.modeshape.jcr.cache.document.DocumentTranslator.getChildReferences(DocumentTranslator.java:887)
	at org.modeshape.jcr.cache.document.LazyCachedNode.getChildReferences(LazyCachedNode.java:449)
	at org.modeshape.jcr.SystemContent.readAllNodeTypes(SystemContent.java:787)
	at org.modeshape.jcr.RepositoryNodeTypeManager.refreshFromSystem(RepositoryNodeTypeManager.java:743)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:1133)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:937)
	at org.modeshape.jcr.JcrRepository.doStart(JcrRepository.java:368)
	at org.modeshape.jcr.JcrRepository.getStartupProblems(JcrRepository.java:286)
	at org.fcrepo.kernel.modeshape.spring.ModeShapeRepositoryFactoryBean.buildRepository(ModeShapeRepositoryFactoryBean.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:732)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.fcrepo.http.commons.FedoraContextLoaderListener.contextInitialized(FedoraContextLoaderListener.java:40)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.simplericity.jettyconsole.DefaultJettyManager.startServer(DefaultJettyManager.java:114)
	at org.simplericity.jettyconsole.JettyConsoleStarter.initConsoleApp(JettyConsoleStarter.java:175)
	at org.simplericity.jettyconsole.JettyConsoleStarter.run(JettyConsoleStarter.java:158)
	at org.simplericity.jettyconsole.JettyConsoleStarter.main(JettyConsoleStarter.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.startJettyConsole(JettyConsoleBootstrapMainClass.java:207)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.run(JettyConsoleBootstrapMainClass.java:103)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.main(JettyConsoleBootstrapMainClass.java:74)
Caused by: org.modeshape.jcr.value.NamespaceException: There is no namespace registered for the prefix "ns010"
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:148)
	... 70 common frames omitted
WARN 12:22:09.013 (XmlWebApplicationContext) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'modeshapeRepofactory': Invocation of init method failed; nested exception is org.fcrepo.kernel.api.exception.RepositoryRuntimeException: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
ERROR 12:22:09.015 (ContextLoader) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'modeshapeRepofactory': Invocation of init method failed; nested exception is org.fcrepo.kernel.api.exception.RepositoryRuntimeException: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:732)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.fcrepo.http.commons.FedoraContextLoaderListener.contextInitialized(FedoraContextLoaderListener.java:40)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.simplericity.jettyconsole.DefaultJettyManager.startServer(DefaultJettyManager.java:114)
	at org.simplericity.jettyconsole.JettyConsoleStarter.initConsoleApp(JettyConsoleStarter.java:175)
	at org.simplericity.jettyconsole.JettyConsoleStarter.run(JettyConsoleStarter.java:158)
	at org.simplericity.jettyconsole.JettyConsoleStarter.main(JettyConsoleStarter.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.startJettyConsole(JettyConsoleBootstrapMainClass.java:207)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.run(JettyConsoleBootstrapMainClass.java:103)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.main(JettyConsoleBootstrapMainClass.java:74)
Caused by: org.fcrepo.kernel.api.exception.RepositoryRuntimeException: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.fcrepo.kernel.modeshape.spring.ModeShapeRepositoryFactoryBean.buildRepository(ModeShapeRepositoryFactoryBean.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 50 common frames omitted
Caused by: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:157)
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:46)
	at org.modeshape.jcr.cache.document.DocumentTranslator.childReferenceFrom(DocumentTranslator.java:966)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences$Medium.<init>(ImmutableChildReferences.java:220)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences.create(ImmutableChildReferences.java:53)
	at org.modeshape.jcr.cache.document.DocumentTranslator.getChildReferences(DocumentTranslator.java:887)
	at org.modeshape.jcr.cache.document.LazyCachedNode.getChildReferences(LazyCachedNode.java:449)
	at org.modeshape.jcr.cache.document.SessionNode.getChildReferences(SessionNode.java:1132)
	at org.modeshape.jcr.SystemContent.store(SystemContent.java:309)
	at org.modeshape.jcr.SystemContent.store(SystemContent.java:286)
	at org.modeshape.jcr.RepositoryNodeTypeManager.registerNodeTypes(RepositoryNodeTypeManager.java:525)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:1138)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:937)
	at org.modeshape.jcr.JcrRepository.doStart(JcrRepository.java:368)
	at org.modeshape.jcr.JcrRepository.getStartupProblems(JcrRepository.java:286)
	at org.fcrepo.kernel.modeshape.spring.ModeShapeRepositoryFactoryBean.buildRepository(ModeShapeRepositoryFactoryBean.java:78)
	... 57 common frames omitted
Caused by: org.modeshape.jcr.value.NamespaceException: There is no namespace registered for the prefix "ns010"
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:148)
	... 72 common frames omitted
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.s.j.JettyConsoleWebappContext@3b6eb2ec{/,file:/private/var/folders/dh/p2mwfqlj3x516wnyyrbjr519p2r_lj/T/fcrepo-webapp-4.7.1-jetty-console.jar_54864/webapp/,STARTING}{/private/var/folders/dh/p2mwfqlj3x516wnyyrbjr519p2r_lj/T/fcrepo-webapp-4.7.1-jetty-console/fcrepo-webapp-4.7.1-jetty-console.jar}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'modeshapeRepofactory': Invocation of init method failed; nested exception is org.fcrepo.kernel.api.exception.RepositoryRuntimeException: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:732)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.fcrepo.http.commons.FedoraContextLoaderListener.contextInitialized(FedoraContextLoaderListener.java:40)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.simplericity.jettyconsole.DefaultJettyManager.startServer(DefaultJettyManager.java:114)
	at org.simplericity.jettyconsole.JettyConsoleStarter.initConsoleApp(JettyConsoleStarter.java:175)
	at org.simplericity.jettyconsole.JettyConsoleStarter.run(JettyConsoleStarter.java:158)
	at org.simplericity.jettyconsole.JettyConsoleStarter.main(JettyConsoleStarter.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.startJettyConsole(JettyConsoleBootstrapMainClass.java:207)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.run(JettyConsoleBootstrapMainClass.java:103)
	at org.simplericity.jettyconsole.JettyConsoleBootstrapMainClass.main(JettyConsoleBootstrapMainClass.java:74)
Caused by: org.fcrepo.kernel.api.exception.RepositoryRuntimeException: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.fcrepo.kernel.modeshape.spring.ModeShapeRepositoryFactoryBean.buildRepository(ModeShapeRepositoryFactoryBean.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 50 more
Caused by: org.modeshape.jcr.value.ValueFormatException: Error converting "ns010:OriginalFile" from String to a Name
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:157)
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:46)
	at org.modeshape.jcr.cache.document.DocumentTranslator.childReferenceFrom(DocumentTranslator.java:966)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences$Medium.<init>(ImmutableChildReferences.java:220)
	at org.modeshape.jcr.cache.document.ImmutableChildReferences.create(ImmutableChildReferences.java:53)
	at org.modeshape.jcr.cache.document.DocumentTranslator.getChildReferences(DocumentTranslator.java:887)
	at org.modeshape.jcr.cache.document.LazyCachedNode.getChildReferences(LazyCachedNode.java:449)
	at org.modeshape.jcr.cache.document.SessionNode.getChildReferences(SessionNode.java:1132)
	at org.modeshape.jcr.SystemContent.store(SystemContent.java:309)
	at org.modeshape.jcr.SystemContent.store(SystemContent.java:286)
	at org.modeshape.jcr.RepositoryNodeTypeManager.registerNodeTypes(RepositoryNodeTypeManager.java:525)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:1138)
	at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:937)
	at org.modeshape.jcr.JcrRepository.doStart(JcrRepository.java:368)
	at org.modeshape.jcr.JcrRepository.getStartupProblems(JcrRepository.java:286)
	at org.fcrepo.kernel.modeshape.spring.ModeShapeRepositoryFactoryBean.buildRepository(ModeShapeRepositoryFactoryBean.java:78)
	... 57 more
Caused by: org.modeshape.jcr.value.NamespaceException: There is no namespace registered for the prefix "ns010"
	at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:148)
	... 72 more
```

**Comment by unnati914** [comment]
could i work on this issue

**Comment by whikloj** [comment]
@unnati914 are you experiencing this issue? I ask because the modeshape software has been removed from Fedora for the 6.0.0 release.

**Comment by unnati914** [comment]
oh okay got it!

**Comment by Surfrdan** [comment]
Fedora 6 is the LTS version now and no longer contains ModeShape. This can be closed
