### ISSUE TITLE
Internal Server Error when getting versions of a version.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo/fcrepo#1271]
On: 4.7.3 | Build #057342a9 (2017-06-08)
When I go to: http://localhost:8988/rest/test/test/original/fcr:versions/version1/fcr:versions

Then I get a 500 error with this stack trace:

```
org.modeshape.jcr.value.ValueFormatException: Error converting "fcr:versions" from String to a Name at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:157) at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:46) at org.modeshape.jcr.value.basic.PathValueFactory.createSegment(PathValueFactory.java:599) at org.modeshape.jcr.value.basic.PathValueFactory.createSegment(PathValueFactory.java:588) at org.modeshape.jcr.AbstractJcrItem.segmentFrom(AbstractJcrItem.java:75) at org.modeshape.jcr.AbstractJcrNode.getNode(AbstractJcrNode.java:803) at org.modeshape.jcr.JcrSystemNode.getNode(JcrSystemNode.java:25) at org.modeshape.jcr.AbstractJcrNode.getNode(AbstractJcrNode.java:101) at org.fcrepo.http.commons.api.rdf.HttpResourceConverter.getNode(HttpResourceConverter.java:266) at org.fcrepo.http.commons.api.rdf.HttpResourceConverter.doForward(HttpResourceConverter.java:120) at org.fcrepo.http.commons.api.rdf.HttpResourceConverter.doForward(HttpResourceConverter.java:78) at com.google.common.base.Converter.correctedDoForward(Converter.java:175) at com.google.common.base.Converter.convert(Converter.java:168) at org.fcrepo.http.api.FedoraBaseResource.getResourceFromPath(FedoraBaseResource.java:90) at org.fcrepo.http.api.FedoraVersions.resource(FedoraVersions.java:166) at org.fcrepo.http.api.FedoraVersions.getVersion(FedoraVersions.java:143) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) at org.glassfish.jersey.internal.Errors.process(Errors.java:315) at org.glassfish.jersey.internal.Errors.process(Errors.java:297) at org.glassfish.jersey.internal.Errors.process(Errors.java:267) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.eclipse.jetty.server.Server.handle(Server.java:497) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610) at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539) at java.lang.Thread.run(Thread.java:745) Caused by: org.modeshape.jcr.value.NamespaceException: There is no namespace registered for the prefix "fcr" at org.modeshape.jcr.value.basic.NameValueFactory.create(NameValueFactory.java:148) ... 61 more 
```

Instead I'd expect to get a 4xx error of some sort.

**Comment by Surfrdan** [comment]
Modeshape is no longer included in Fedora 6 which is the LTS version of Fedora. Closing
