### ISSUE TITLE
Null Pointer Exception on Solr Reindex

### ISSUE THREAD

**Issue by pghorpade** [fcrepo/fcrepo#1654]
We are running Hyrax/Samvera instance [internal application] in production and blacklight for public access for UCLA DLP

We had to reindex all the content in production, but it is failing on this one record all the time.

For fedora, I see a version of 4.7.5 
For modeshape, I see 5.4.0 in the WEB-INF/lib

Here are the logs from fcrepo.log

```
java.lang.NullPointerException: null
at org.modeshape.jcr.cache.document.LazyCachedNode.getPrimaryType(LazyCachedNode.java:339)
at org.modeshape.jcr.JcrSession.node(JcrSession.java:556)
at org.modeshape.jcr.JcrSession.node(JcrSession.java:534)
at org.modeshape.jcr.JcrSession.node(JcrSession.java:500)
at org.modeshape.jcr.JcrSession.node(JcrSession.java:478)
at org.modeshape.jcr.JcrSession.getNodeByIdentifier(JcrSession.java:799)
at org.modeshape.jcr.JcrSession.getNodeByIdentifier(JcrSession.java:126)
at org.fcrepo.kernel.modeshape.rdf.converters.ValueConverter.nodeForValue(ValueConverter.java:183)
```
Here is the record on our public site https://ursus.library.ucla.edu/catalog/853w6200zz-89112.

please advice.
Thank you

**Comment by Surfrdan** [comment]
Modeshape is no longer part of Fedora and Fedora 6 is the LTS version now. This also feels like a data issue to me if only one object was affected. Either way, after 3 years of no response I'm closing this
