### ISSUE TITLE
Occasionally, hangs when tomcat is shutting down due to non-serializable class in session

### ISSUE THREAD

**Issue by nigelgbanks** [fcrepo/fcrepo#2031]
```log
WARN 17:12:29.601 [ActiveMQ ShutdownHook] (Transport) Transport Connection to: vm://localhost#0 failed
org.apache.activemq.transport.TransportDisposedIOException: peer (vm://localhost#0) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:233)
	at org.apache.activemq.transport.vm.VMTransportServer$1.stop(VMTransportServer.java:81)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:72)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:72)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.util.ServiceStopper.stop(ServiceStopper.java:41)
	at org.apache.activemq.network.DemandForwardingBridgeSupport.stop(DemandForwardingBridgeSupport.java:330)
	at org.apache.activemq.network.DiscoveryNetworkConnector.handleStop(DiscoveryNetworkConnector.java:227)
	at org.apache.activemq.network.NetworkConnector$1.doStop(NetworkConnector.java:65)
	at org.apache.activemq.util.ServiceSupport.stop(ServiceSupport.java:71)
	at org.apache.activemq.network.NetworkConnector.stop(NetworkConnector.java:170)
	at org.apache.activemq.util.ServiceStopper.stop(ServiceStopper.java:41)
	at org.apache.activemq.broker.BrokerService.stopAllConnectors(BrokerService.java:2260)
	at org.apache.activemq.broker.BrokerService.stop(BrokerService.java:857)
	at org.apache.activemq.xbean.XBeanBrokerService.stop(XBeanBrokerService.java:122)
	at org.apache.activemq.broker.BrokerService.containerShutdown(BrokerService.java:2599)
	at org.apache.activemq.broker.BrokerService$7.run(BrokerService.java:2566)
12-Mar-2023 17:12:29.600 WARNING [Thread-11] org.apache.catalina.session.StandardSession.doWriteObject Cannot serialize session attribute [org.apache.shiro.subject.support.DefaultSubjectContext_PRINCIPALS_SESSION_KEY] for session [B831663225D5CF2C102F740E2F7B9373]
	java.io.NotSerializableException: org.fcrepo.auth.common.ContainerRolesPrincipalProvider$ContainerRolesPrincipal
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at java.base/java.util.HashSet.writeObject(HashSet.java:290)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at java.base/java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:334)
		at java.base/java.util.HashMap.writeObject(HashMap.java:1497)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
		at java.base/java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:443)
		at org.apache.shiro.subject.SimplePrincipalCollection.writeObject(SimplePrincipalCollection.java:274)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at org.apache.catalina.session.StandardSession.doWriteObject(StandardSession.java:1761)
		at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1067)
		at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:317)
		at org.apache.catalina.session.StandardManager.unload(StandardManager.java:268)
		at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:384)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5459)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:983)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:983)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:495)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:982)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
		at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:996)
12-Mar-2023 17:12:29.606 WARNING [Thread-11] org.apache.catalina.session.StandardSession.doWriteObject Cannot serialize session attribute [org.apache.shiro.subject.support.DefaultSubjectContext_PRINCIPALS_SESSION_KEY] for session [D5CCE5EEACD8A8A2907857BE9F6258F4]
	java.io.NotSerializableException: org.fcrepo.auth.common.ContainerRolesPrincipalProvider$ContainerRolesPrincipal
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at java.base/java.util.HashSet.writeObject(HashSet.java:290)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at java.base/java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:334)
		at java.base/java.util.HashMap.writeObject(HashMap.java:1497)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
		at java.base/java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:443)
		at org.apache.shiro.subject.SimplePrincipalCollection.writeObject(SimplePrincipalCollection.java:274)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
		at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
		at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
		at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
		at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
		at org.apache.catalina.session.StandardSession.doWriteObject(StandardSession.java:1761)
		at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1067)
		at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:317)
		at org.apache.catalina.session.StandardManager.unload(StandardManager.java:268)
		at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:384)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5459)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:983)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
		at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:983)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:495)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:982)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.startup.Catalina.stop(Catalina.java:849)
		at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:996)
```

The last warning just repeatedly prints.

**Comment by nigelgbanks** [comment]
Static classes are not serializable? https://github.com/fcrepo/fcrepo/blob/4ebc0b397d1aac321820fecf0f27532df129a826/fcrepo-auth-common/src/main/java/org/fcrepo/auth/common/ContainerRolesPrincipalProvider.java#L34-L73

**Comment by whikloj** [comment]
Wondering if this is a similar but different version of this https://fedora-repository.atlassian.net/browse/FCREPO-3809

**Comment by nigelgbanks** [comment]
https://tomcat.apache.org/tomcat-9.0-doc/config/manager.html#Persistence_Across_Restarts

**Comment by nigelgbanks** [comment]
I was able to get this to work around this by disabling the persistent session. 

I added the following file `webapps/fcrepo/META-INF/context.xml`:

```xml
<Context>
    <Manager pathname="" />
</Context>
```

**Comment by nigelgbanks** [comment]
> Wondering if this is a similar but different version of this https://fedora-repository.atlassian.net/browse/FCREPO-3809

Yes, this seems related, as it also has to do with the session manager, though in that case, it is trying to initialize it rather than save it. I think the same workaround I have here of disabling persistence entirely could work.

**Comment by whikloj** [comment]
@nigelgbanks I think we needed to make them implement `Serializable` so Tomcat would try to serialize them.

**Comment by nigelgbanks** [comment]
That would work as well

**Comment by whikloj** [comment]
Closing as we believe this has been resolved by either or both of https://github.com/fcrepo/fcrepo/pull/2038 and https://github.com/fcrepo-exts/fcrepo-docker/pull/15
