### ISSUE TITLE
Inspect message demo is out of date (Python)

### ISSUE THREAD

**Issue by ross-spencer** [fcrepo/fcrepo#2048]
I'm not sure when the Stomp API changed but the inspect message demo [here](https://wiki.lyrasis.org/display/FEDORA6x/Inspect+Event+Messages) currently returns the error:

```text
Exception in thread Thread-1 (__receiver_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/r0ss/git/ross-spencer/book/content/message_listener/venv/lib/python3.10/site-packages/stomp/transport.py", line 341, in __receiver_loop
    self.process_frame(f, frame)
  File "/home/r0ss/git/ross-spencer/book/content/message_listener/venv/lib/python3.10/site-packages/stomp/transport.py", line 190, in process_frame
    self.notify(frame_type, f)
  File "/home/r0ss/git/ross-spencer/book/content/message_listener/venv/lib/python3.10/site-packages/stomp/transport.py", line 243, in notify
    notify_func(frame)
TypeError: Listener.on_message() missing 1 required positional argument: 'body'
```

The current code:

```python
import stomp
import signal

class Listener(stomp.ConnectionListener):
    def on_message(self, headers, body):
        print ("\n\nIncoming Message")
        print ("--Headers:")
        for k, v in headers.items():
            if k.startswith("org.fcrepo.jms"):
                print (f"{k} => {v}")

        print ("\n--Body:")
        print (body)
connection = stomp.Connection(host_and_ports=[('localhost', 61613)])
connection.set_listener('', Listener())
#connection.start()
connection.connect()
connection.subscribe(id="abcd", destination='/topic/fedora')
while True: 
    signal.pause()
```

I had a brief look and it can be changed to something like this and it will output the same:

```python
"""Fedora (fcrepo) 6 message listener demo."""

import stomp
import signal


class Listener(stomp.ConnectionListener):
    def on_message(self, frame):
        print("Incoming Message")
        print("\n--Headers:")
        for key, value in frame.headers.items():
            if key.startswith("org.fcrepo.jms"):
                print(f"{key} => {value}")
        print("\n--Body:")
        print(frame.body)


connection = stomp.Connection(host_and_ports=[("localhost", 61613)])
connection.set_listener("", Listener())
connection.connect()
connection.subscribe(id="abcd", destination="/topic/fedora")
while True:
    signal.pause()
```

**Comment by Surfrdan** [comment]
Thanks for spotting this @ross-spencer and apologies for not updating this issue sooner. I've updated the attached fie on the wiki

**Comment by ross-spencer** [comment]
Awesome, looking forward to giving it a whirl @Surfrdan many thanks!
